Repository GoogleCloudPlatform/ruby-docs-samples, pull requests merged in 2018-05, with the labels that each got.

#277 Logging: update region tags
  stackdriver/Gemfile
  stackdriver/logging.ru
  stackdriver/rails_configuration.rb
  stackdriver/shared_config.ru
Labels: do-not-merge

#282 [Storage] KMS integration samples
  storage/Gemfile.lock
  storage/README.md
  storage/buckets.rb
  storage/files.rb
  storage/spec/buckets_spec.rb
  storage/spec/files_spec.rb
Labels: new-sample

#283 [Storage] Fix error in KMS tests
  storage/spec/buckets_spec.rb
  storage/spec/files_spec.rb
Labels: bug
