Repository GoogleCloudPlatform/ruby-docs-samples, pull requests merged in 2020-10, with the labels that each got.

#664 feat: Add pub/sub ordering keys examples
  pubsub/spec/topics_spec.rb
  pubsub/topics.rb
Labels: api: pubsub, cla: yes, samples

#655 Adding functions_concepts_scopes sample
  functions/concepts/scopes/Gemfile
  functions/concepts/scopes/Gemfile.lock
  functions/concepts/scopes/app.rb
  functions/test/concepts/scopes_test.rb
Labels: cla: yes, samples

#674 fix(functions): Fix rubocop errors
  functions/concepts/scopes/app.rb
  functions/slack/app.rb
  functions/test/slack_test.rb
Labels: api: cloudfunctions, cla: yes, samples

#677 delete firestore samples
  .rubocop.yml
  firestore/Gemfile
  firestore/Gemfile.lock
  firestore/README.md
  firestore/Rakefile
  firestore/acceptance/add_data_test.rb
  firestore/acceptance/data_model_test.rb
  firestore/acceptance/delete_data_test.rb
  firestore/acceptance/distributed_counters_test.rb
  firestore/acceptance/get_data_test.rb
  firestore/acceptance/helper.rb
  firestore/acceptance/order_limit_data_test.rb
  firestore/acceptance/paginate_data_test.rb
  firestore/acceptance/query_data_test.rb
  firestore/acceptance/quickstart_test.rb
  firestore/acceptance/transactions_and_batched_writes_test.rb
  firestore/add_data.rb
  firestore/data_model.rb
  firestore/delete_data.rb
  firestore/distributed_counters.rb
  firestore/get_data.rb
  firestore/order_limit_data.rb
  firestore/paginate_data.rb
  firestore/query_data.rb
  firestore/quickstart.rb
  firestore/transactions_and_batched_writes.rb
Labels: cla: yes

#678 fix(functions): Update scopes sample to use the on_startup construct
  functions/concepts/scopes/app.rb
  functions/test/concepts/scopes_test.rb
Labels: api: cloudfunctions, cla: yes, samples

#675 feat: Add functions_http_form_data sample
  functions/http/form_data/Gemfile
  functions/http/form_data/Gemfile.lock
  functions/http/form_data/app.rb
  functions/test/http/form_data_test.rb
Labels: cla: yes, samples

#671 feat: Add functions_firebase_auth sample
  functions/firebase/auth/Gemfile
  functions/firebase/auth/Gemfile.lock
  functions/firebase/auth/app.rb
  functions/test/firebase/auth_test.rb
Labels: cla: yes, samples

#670 feat: Add functions_firebase_rtdb sample
  functions/firebase/rtdb/Gemfile
  functions/firebase/rtdb/Gemfile.lock
  functions/firebase/rtdb/app.rb
  functions/test/firebase/rtdb_test.rb
Labels: cla: yes, samples

#672 feat: Add functions_firebase_analytics sample
  functions/firebase/analytics/Gemfile
  functions/firebase/analytics/Gemfile.lock
  functions/firebase/analytics/app.rb
  functions/test/firebase/analytics_test.rb
Labels: cla: yes, samples

#680 Update pubsub test service app.yaml and listener.rb
  pubsub/app.yaml
  pubsub/listener.rb
Labels: api: pubsub, cla: yes

#683 pubsub: delete duplicate sample for pubsub_publisher_batch_settings
  pubsub/README.md
  pubsub/spec/topics_spec.rb
  pubsub/topics.rb
Labels: api: pubsub, cla: yes

#681 chore: enable snippet-bot
  .github/snippet-bot.yml
Labels: cla: yes, samples

#685 fix mis-matched region tags
  bigtable/hello_world.rb
  bigtable/read_samples.rb
Labels: cla: yes

#686 fix(functions): Fix event function terminology and use context-provided logger
  functions/Gemfile.lock
  functions/firebase/firestore/app.rb
  functions/helloworld/pubsub/app.rb
  functions/helloworld/storage/app.rb
  functions/tips/infinite_retries/app.rb
  functions/tips/retry/app.rb
Labels: api: cloudfunctions, cla: yes, samples

#691 samples: disable flaky iot test
  iot/spec/iot_spec.rb
Labels: cla: yes, samples

#689 remove bigquery samples
  bigquery/simple_app/.rubocop.yml
  bigquery/simple_app/Gemfile
  bigquery/simple_app/Gemfile.lock
  bigquery/simple_app/README.md
  bigquery/simple_app/Rakefile
  bigquery/simple_app/acceptance/stackoverflow_test.rb
  bigquery/simple_app/stackoverflow.rb
  bigquery/snippets/.rubocop.yml
  bigquery/snippets/Gemfile
  bigquery/snippets/Gemfile.lock
  bigquery/snippets/README.md
  bigquery/snippets/Rakefile
  bigquery/snippets/acceptance/browse_table_test.rb
  bigquery/snippets/acceptance/create_dataset_test.rb
  bigquery/snippets/acceptance/create_table_test.rb
  bigquery/snippets/acceptance/delete_dataset_and_contents_test.rb
  bigquery/snippets/acceptance/delete_dataset_test.rb
  bigquery/snippets/acceptance/delete_table_test.rb
  bigquery/snippets/acceptance/extract_table_test.rb
  bigquery/snippets/acceptance/helper.rb
  bigquery/snippets/acceptance/list_datasets_test.rb
  bigquery/snippets/acceptance/list_tables_test.rb
  bigquery/snippets/acceptance/load_from_file_test.rb
  bigquery/snippets/acceptance/load_table_gcs_csv_test.rb
  bigquery/snippets/acceptance/load_table_gcs_json_autodetect_test.rb
  bigquery/snippets/acceptance/load_table_gcs_json_test.rb
  bigquery/snippets/acceptance/load_table_gcs_json_truncate_test.rb
  bigquery/snippets/acceptance/load_table_gcs_orc_test.rb
  bigquery/snippets/acceptance/load_table_gcs_orc_truncate_test.rb
  bigquery/snippets/acceptance/query_test.rb
  bigquery/snippets/acceptance/table_insert_rows_test.rb
  bigquery/snippets/browse_table.rb
  bigquery/snippets/create_dataset.rb
  bigquery/snippets/create_table.rb
  bigquery/snippets/delete_dataset.rb
  bigquery/snippets/delete_dataset_and_contents.rb
  bigquery/snippets/delete_table.rb
  bigquery/snippets/extract_table.rb
  bigquery/snippets/list_datasets.rb
  bigquery/snippets/list_tables.rb
  bigquery/snippets/load_from_file.rb
  bigquery/snippets/load_table_gcs_csv.rb
  bigquery/snippets/load_table_gcs_json.rb
  bigquery/snippets/load_table_gcs_json_autodetect.rb
  bigquery/snippets/load_table_gcs_json_truncate.rb
  bigquery/snippets/load_table_gcs_orc.rb
  bigquery/snippets/load_table_gcs_orc_truncate.rb
  bigquery/snippets/query.rb
  bigquery/snippets/resources/people.csv
  bigquery/snippets/table_insert_rows.rb
Labels: cla: yes, samples

#688 pubsub: Add DLQ, detach, error and lease samples
  pubsub/Gemfile.lock
  pubsub/acceptance/subscriptions_test.rb
  pubsub/acceptance/topics_test.rb
  pubsub/subscriptions.rb
  pubsub/topics.rb
Labels: api: pubsub, cla: yes, samples

#693 docs: add gh pr template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: api: docs, cla: yes, samples
