Repository GoogleCloudPlatform/ruby-docs-samples, pull requests merged in 2020-12, with the labels that each got.

#574 datastore: delete
  datastore/Gemfile
  datastore/Gemfile.lock
  datastore/README.md
  datastore/Rakefile
  datastore/acceptance/helper.rb
  datastore/acceptance/quickstart_test.rb
  datastore/acceptance/sample_test.rb
  datastore/acceptance/tasks_test.rb
  datastore/index.yaml
  datastore/quickstart.rb
  datastore/sample.rb
  datastore/tasks.rb
Labels: api: datastore, cla: yes, samples

#715 chore(functions): make scopes sample consistent with other languages
  functions/Gemfile.lock
  functions/test/tips/scopes_test.rb
  functions/tips/scopes/Gemfile
  functions/tips/scopes/Gemfile.lock
  functions/tips/scopes/app.rb
Labels: api: cloudfunctions, cla: yes, samples

#720 use v1
  servicedirectory/Gemfile.lock
  servicedirectory/servicedirectory.rb
Labels: api: servicedirectory, cla: yes, samples

#710 fix: update region tags for eventarc generic sample
  eventarc/generic/Dockerfile
  eventarc/generic/app.rb
Labels: cla: yes, samples

#709 Engelke gae standard
  appengine/standard-datastore/Gemfile
  appengine/standard-datastore/Gemfile.lock
  appengine/standard-datastore/README.md
  appengine/standard-datastore/app.rb
  appengine/standard-datastore/app.yaml
  appengine/standard-datastore/spec/datastore_spec.rb
  appengine/standard-storage/Gemfile
  appengine/standard-storage/Gemfile.lock
  appengine/standard-storage/README.md
  appengine/standard-storage/app.rb
  appengine/standard-storage/app.yaml
  appengine/standard-storage/spec/ruby-storage-test-upload.txt
  appengine/standard-storage/spec/storage_spec.rb
Labels: cla: yes, samples
