Repository GoogleCloudPlatform/ruby-docs-samples, pull requests merged in 2020-05, with the labels that each got.

#566 chore (texttospeech): update tests in the samples for texttospeech
  texttospeech/.rspec
  texttospeech/Gemfile
  texttospeech/Gemfile.lock
  texttospeech/Rakefile
  texttospeech/acceptance/list_voices_test.rb
  texttospeech/acceptance/quickstart_test.rb
  texttospeech/acceptance/synthesize_file_test.rb
  texttospeech/acceptance/synthesize_text_test.rb
Labels: cla: yes

#538 spanner: backup and restore examples and tests
  spanner/Gemfile.lock
  spanner/README.md
  spanner/spanner_samples.rb
  spanner/spec/spanner_samples_spec.rb
  spanner/spec/spec_helper.rb
Labels: api: spanner, cla: yes

#572 fix(video): change local tests to use different file and only check for success
  video/Gemfile.lock
  video/spec/video_samples_spec.rb
Labels: cla: yes

#571 fix(jobs): remove unused, broken sample
  jobs/quickstart.rb
  jobs/spec/quickstart_spec.rb
Labels: cla: yes

#570 fix(translate): fix broken test
  translate/Gemfile.lock
  translate/spec/quickstart_spec.rb
Labels: cla: yes

#567 chore (dlp): update tests in the samples for dlp
  dlp/.rspec
  dlp/Gemfile
  dlp/Gemfile.lock
  dlp/Rakefile
  dlp/acceptance/data/test.txt
  dlp/acceptance/quickstart_test.rb
  dlp/acceptance/sample_test.rb
  dlp/spec/data/test.txt
Labels: cla: yes

#568 Delete speech samples
  speech/.rspec
  speech/Gemfile
  speech/Gemfile.lock
  speech/README.md
  speech/quickstart.rb
  speech/resources/Google_Gnome.wav
  speech/resources/audio.flac
  speech/resources/audio.raw
  speech/resources/audio2.raw
  speech/resources/commercial_mono.wav
  speech/resources/multi.wav
  speech/resources/quit.raw
  speech/spec/quickstart_spec.rb
  speech/spec/speech_samples_spec.rb
  speech/speech_samples.rb
Labels: automerge, cla: yes

#545 Add ruby client library samples for Service Directory
  servicedirectory/Gemfile
  servicedirectory/Gemfile.lock
  servicedirectory/README.md
  servicedirectory/quickstart.rb
  servicedirectory/servicedirectory.rb
  servicedirectory/spec/quickstart_spec.rb
  servicedirectory/spec/servicedirectory_spec.rb
Labels: cla: yes

#563 bigquerydatatransfer: delete from ruby-docs-samples
  bigquerydatatransfer/Gemfile
  bigquerydatatransfer/Gemfile.lock
  bigquerydatatransfer/Rakefile
  bigquerydatatransfer/acceptance/helper.rb
  bigquerydatatransfer/acceptance/quickstart_test.rb
  bigquerydatatransfer/quickstart.rb
Labels: api: bigquerydatatransfer, cla: yes

#550 remove storage samples
  storage/Gemfile
  storage/Gemfile.lock
  storage/README.md
  storage/acceptance/acls_test.rb
  storage/acceptance/buckets_test.rb
  storage/acceptance/data/file.txt
  storage/acceptance/files_test.rb
  storage/acceptance/helper.rb
  storage/acceptance/hmac_test.rb
  storage/acceptance/iam_test.rb
  storage/acceptance/quickstart_test.rb
  storage/acls.rb
  storage/buckets.rb
  storage/files.rb
  storage/hmac.rb
  storage/iam.rb
  storage/quickstart.rb
Labels: cla: yes

#577 Added FreeTDS dependency for SQL Server to testing Dockerfiles
  .kokoro/docker/ruby-2.4/Dockerfile
  .kokoro/docker/ruby-2.5/Dockerfile
  .kokoro/docker/ruby-2.6/Dockerfile
Labels: cla: yes

#580 dlp: delete from ruby-docs-samples
  dlp/Gemfile
  dlp/Gemfile.lock
  dlp/README.md
  dlp/acceptance/quickstart_test.rb
  dlp/acceptance/sample_test.rb
  dlp/quickstart.rb
  dlp/sample.rb
Labels: cla: yes

#579 texttospeech: delete from ruby-docs-samples
  texttospeech/Gemfile
  texttospeech/Gemfile.lock
  texttospeech/README.md
  texttospeech/acceptance/list_voices_test.rb
  texttospeech/acceptance/quickstart_test.rb
  texttospeech/acceptance/synthesize_file_test.rb
  texttospeech/acceptance/synthesize_text_test.rb
  texttospeech/list_voices.rb
  texttospeech/quickstart.rb
  texttospeech/resources/hello.ssml
  texttospeech/resources/hello.txt
  texttospeech/synthesize_file.rb
  texttospeech/synthesize_text.rb
Labels: cla: yes

#582 Fixes badges for Ruby
  README.md
  securitycenter/Gemfile
Labels: cla: yes

#587 Delete scheduler, which has been moved to google-cloud-ruby
  scheduler/Gemfile
  scheduler/Gemfile.lock
  scheduler/app.rb
  scheduler/app.yaml
  scheduler/create_job.rb
  scheduler/delete_job.rb
  scheduler/spec/scheduler_spec.rb
Labels: cla: yes

#586 Delete some straggling files from DLP
  dlp/Rakefile
  dlp/acceptance/data/test.txt
Labels: cla: yes

#584 Delete dialogflow, which has previously been moved to google-cloud-ruby
  dialogflow/Gemfile
  dialogflow/Gemfile.lock
  dialogflow/README.md
  dialogflow/Rakefile
  dialogflow/acceptance/context_management_test.rb
  dialogflow/acceptance/detect_intent_audio_test.rb
  dialogflow/acceptance/detect_intent_stream_test.rb
  dialogflow/acceptance/detect_intent_texts_test.rb
  dialogflow/acceptance/entity_management_test.rb
  dialogflow/acceptance/entity_type_management_test.rb
  dialogflow/acceptance/helper.rb
  dialogflow/acceptance/intent_management_test.rb
  dialogflow/acceptance/session_entity_type_management_test.rb
  dialogflow/context_management.rb
  dialogflow/detect_intent_audio.rb
  dialogflow/detect_intent_stream.rb
  dialogflow/detect_intent_texts.rb
  dialogflow/entity_management.rb
  dialogflow/entity_type_management.rb
  dialogflow/intent_management.rb
  dialogflow/resources/230pm.wav
  dialogflow/resources/RoomReservation.zip
  dialogflow/resources/book_a_room.wav
  dialogflow/resources/half_an_hour.wav
  dialogflow/resources/mountain_view.wav
  dialogflow/resources/today.wav
  dialogflow/resources/two_people.wav
  dialogflow/session_entity_type_management.rb
Labels: cla: yes

#585 Delete securitycenter, which has been moved to google-cloud-ruby
  securitycenter/.rspec
  securitycenter/Gemfile
  securitycenter/Gemfile.lock
  securitycenter/README.md
  securitycenter/notification.rb
  securitycenter/spec/notification_spec.rb
  securitycenter/spec/spec_helper.rb
Labels: cla: yes

#591 chore: Add minitest-focus
  Gemfile
  bigquery/simple_app/Gemfile
  bigquery/simple_app/Gemfile.lock
  bigquery/simple_app/acceptance/stackoverflow_test.rb
  bigquery/snippets/Gemfile.lock
  datastore/Gemfile.lock
  logging/Gemfile
  logging/Gemfile.lock
  logging/acceptance/helper.rb
Labels: cla: yes

#589 kms: convert to minitest
  kms/.rspec
  kms/.rubocop.yml
  kms/Gemfile
  kms/Gemfile.lock
  kms/README.md
  kms/Rakefile
  kms/acceptance/snippets_test.rb
  kms/snippets.rb
  kms/spec/snippets_spec.rb
Labels: api: cloudkms, cla: yes
