Repository GoogleCloudPlatform/ruby-docs-samples, pull requests merged in 2020-09, with the labels that each got.

#644 Update region tags
  run/helloworld/Dockerfile
  run/helloworld/app.rb
Labels: cla: yes, samples

#647 chore(functions): replace helloGcs sample with helloGcsGeneric
  functions/helloworld/storage/app.rb
  functions/helloworld/storage_generic/Gemfile
  functions/helloworld/storage_generic/Gemfile.lock
  functions/helloworld/storage_generic/app.rb
  functions/test/helloworld/storage_generic_test.rb
  functions/test/helloworld/storage_test.rb
Labels: api: cloudfunctions, cla: yes, samples

#652 feat(spanner): add numeric samples
  spanner/Gemfile.lock
  spanner/spanner_samples.rb
  spanner/spec/spanner_samples_spec.rb
Labels: api: spanner, cla: yes, samples

#650 feat: add ruby run events pubsub sample
  run/events-pubsub/.dockerignore
  run/events-pubsub/.gcloudignore
  run/events-pubsub/Dockerfile
  run/events-pubsub/Gemfile
  run/events-pubsub/Gemfile.lock
  run/events-pubsub/README.md
  run/events-pubsub/app.rb
  run/events-pubsub/e2e_test_setup.yaml
  run/events-pubsub/spec/run_events_pubsub_handler_spec.rb
Labels: cla: yes, samples

#668 fix(logging): Try to deflake the list_log_entries test
  logging/Gemfile.lock
  logging/acceptance/sample_test.rb
  logging/sample.rb
Labels: cla: yes

#667 Eventarc Quickstart Brushup
  eventarc/pubsub/.dockerignore
  eventarc/pubsub/.gcloudignore
  eventarc/pubsub/Dockerfile
  eventarc/pubsub/Gemfile
  eventarc/pubsub/Gemfile.lock
  eventarc/pubsub/README.md
  eventarc/pubsub/app.rb
  eventarc/pubsub/e2e_test_setup.yaml
  eventarc/pubsub/spec/run_events_pubsub_handler_spec.rb
Labels: automerge, cla: yes, samples

#665 chore: Update functions_framework dependency to 0.7
  Rakefile
  functions/Gemfile
  functions/Gemfile.lock
  functions/concepts/filesystem/Gemfile
  functions/concepts/filesystem/Gemfile.lock
  functions/concepts/requests/Gemfile
  functions/concepts/requests/Gemfile.lock
  functions/concepts/stateless/Gemfile
  functions/concepts/stateless/Gemfile.lock
  functions/firebase/firestore/Gemfile
  functions/firebase/firestore/Gemfile.lock
  functions/helloworld/get/Gemfile
  functions/helloworld/get/Gemfile.lock
  functions/helloworld/http/Gemfile
  functions/helloworld/http/Gemfile.lock
  functions/helloworld/log/Gemfile
  functions/helloworld/log/Gemfile.lock
  functions/helloworld/pubsub/Gemfile
  functions/helloworld/pubsub/Gemfile.lock
  functions/helloworld/storage/Gemfile
  functions/helloworld/storage/Gemfile.lock
  functions/http/content/Gemfile
  functions/http/content/Gemfile.lock
  functions/http/cors/Gemfile
  functions/http/cors/Gemfile.lock
  functions/http/method/Gemfile
  functions/http/method/Gemfile.lock
  functions/tips/infinite_retries/Gemfile
  functions/tips/infinite_retries/Gemfile.lock
  functions/tips/retry/Gemfile
  functions/tips/retry/Gemfile.lock
Labels: cla: yes, samples

#658 feat: Add functions_env_vars sample
  functions/env_vars/Gemfile
  functions/env_vars/Gemfile.lock
  functions/env_vars/app.rb
  functions/test/env_vars_test.rb
Labels: cla: yes, samples
