Repository GoogleCloudPlatform/ruby-docs-samples, pull requests merged in 2021-03, with the labels that each got.

#760 samples(spanner): PITR samples backup fix
  spanner/spanner_samples.rb
  spanner/spec/spanner_samples_spec.rb
Labels: cla: yes, samples

#761 samples(spanner): parameterise create backup
  spanner/spanner_samples.rb
  spanner/spec/spanner_samples_spec.rb
Labels: api: spanner, cla: yes, samples

#752 chore: use common docker images
  .kokoro/presubmit/ruby-2.5.cfg
  .kokoro/presubmit/ruby-2.6.cfg
  .kokoro/presubmit/ruby-2.7.cfg
  .kokoro/presubmit/ruby-3.0.cfg
  .kokoro/system_tests/ruby-2.5.cfg
  .kokoro/system_tests/ruby-2.6.cfg
  .kokoro/system_tests/ruby-2.7.cfg
  .kokoro/system_tests/ruby-3.0.cfg
  spec/kokoro-run-all.sh
Labels: cla: yes, do-not-merge, samples

#764 chore: give presubmit and system_tests their own common.cfg
  .kokoro/presubmit/common.cfg
  .kokoro/presubmit/ruby-2.5.cfg
  .kokoro/presubmit/ruby-2.6.cfg
  .kokoro/presubmit/ruby-2.7.cfg
  .kokoro/presubmit/ruby-3.0.cfg
  .kokoro/system_tests/common.cfg
  .kokoro/system_tests/ruby-2.6.cfg
  .kokoro/system_tests/ruby-2.7.cfg
  .kokoro/system_tests/ruby-3.0.cfg
Labels: cla: yes, samples

#767 Revert "feat: Implement functions_firebase_reactive sample"
  .rubocop.yml
  functions/Gemfile
  functions/Gemfile.lock
  functions/firebase/reactive/Gemfile
  functions/firebase/reactive/Gemfile.lock
  functions/firebase/reactive/app.rb
  functions/slack/Gemfile
  functions/slack/Gemfile.lock
  functions/test/firebase/reactive_test.rb
Labels: cla: yes, samples

#766 feat: Implement functions_firebase_remote_config sample
  functions/firebase/remote_config/Gemfile
  functions/firebase/remote_config/Gemfile.lock
  functions/firebase/remote_config/app.rb
  functions/test/firebase/remote_config_test.rb
Labels: cla: yes, samples

#727 chore(GAE flex): rm unused sql samples
  appengine/cloudsql-mysql/.rspec
  appengine/cloudsql-mysql/Gemfile
  appengine/cloudsql-mysql/Gemfile.lock
  appengine/cloudsql-mysql/README.md
  appengine/cloudsql-mysql/app.rb
  appengine/cloudsql-mysql/app.yaml
  appengine/cloudsql-mysql/create_tables.rb
  appengine/cloudsql-mysql/spec/cloudsql_spec.rb
  appengine/cloudsql-mysql/spec/end_to_end_spec.rb
  appengine/cloudsql-postgres/.rspec
  appengine/cloudsql-postgres/Gemfile
  appengine/cloudsql-postgres/Gemfile.lock
  appengine/cloudsql-postgres/README.md
  appengine/cloudsql-postgres/app.rb
  appengine/cloudsql-postgres/app.yaml
  appengine/cloudsql-postgres/create_tables.rb
  appengine/cloudsql-postgres/spec/cloudsql_spec.rb
  appengine/cloudsql-postgres/spec/end_to_end_spec.rb
  appengine/cloudsql/.rspec
  appengine/cloudsql/Gemfile
  appengine/cloudsql/Gemfile.lock
  appengine/cloudsql/README.md
  appengine/cloudsql/app.rb
  appengine/cloudsql/app.yaml
  appengine/cloudsql/create_tables.rb
  appengine/cloudsql/spec/cloudsql_spec.rb
Labels: cla: yes, samples

#728 chore(GAE): remove unused redis sample
  appengine/memcache/Gemfile
  appengine/memcache/Gemfile.lock
  appengine/memcache/README.md
  appengine/memcache/app.rb
  appengine/memcache/app.yaml
  appengine/memcache/spec/memcache_spec.rb
Labels: cla: yes, samples

#729 chore(GAE flex): rm unused email samples
  appengine/mailgun/Gemfile
  appengine/mailgun/Gemfile.lock
  appengine/mailgun/README.md
  appengine/mailgun/app.rb
  appengine/mailgun/app.yaml
  appengine/mailgun/example-attachment.txt
  appengine/mailgun/spec/mailgun_spec.rb
  appengine/sendgrid/Gemfile
  appengine/sendgrid/Gemfile.lock
  appengine/sendgrid/README.md
  appengine/sendgrid/app.rb
  appengine/sendgrid/app.yaml
  appengine/sendgrid/spec/sendgrid_spec.rb
Labels: cla: yes, samples

#779 chore(functions): remove RTDB path params
  functions/firebase/rtdb/app.rb
Labels: api: cloudfunctions, cla: yes, samples

#718 Adding TCP tests for Cloud SQL samples
  cloud-sql/mysql/activerecord/bin/run_tests
  cloud-sql/mysql/activerecord/config/database.yml
  cloud-sql/mysql/activerecord/config/puma.rb
  cloud-sql/postgres/activerecord/bin/run_tests
  cloud-sql/postgres/activerecord/config/database.yml
  cloud-sql/postgres/activerecord/spec/controllers/votes_spec.rb
  cloud-sql/sqlserver/activerecord/bin/run_tests
  spec/kokoro-run-all.sh
Labels: cla: yes, samples

#781 chore: use latest docker image
  .kokoro/system_tests/ruby-2.5.cfg
Labels: cla: yes, samples

#782 fix: skip logging test if there is too much delay
  logging/acceptance/sample_test.rb
Labels: cla: yes, samples
