Repository GoogleCloudPlatform/ruby-docs-samples, pull requests merged in 2021-01, with the labels that each got.

#725 fix(pubsub): Reduce sleep in pubsub_subscriber_sync_pull_with_lease
  pubsub/Gemfile.lock
  pubsub/subscriptions.rb
Labels: api: pubsub, cla: yes, samples

#724 feat: Add GAE Flex Pub/Sub Auth Push sample
  appengine/pubsub/Gemfile
  appengine/pubsub/Gemfile.lock
  appengine/pubsub/app.rb
  appengine/pubsub/app.standard.yaml
  appengine/pubsub/spec/fixtures/private_key.pem
  appengine/pubsub/spec/fixtures/public_cert.pem
  appengine/pubsub/spec/pubsub_spec.rb
Labels: cla: yes, samples

#716 Add error if env var is not set
  run/helloworld/Dockerfile
  run/helloworld/Gemfile.lock
  run/helloworld/README.md
  run/helloworld/spec/e2e_spec.rb
Labels: automerge, cla: yes, samples
