Repository GoogleCloudPlatform/ruby-docs-samples, pull requests merged in 2022-08, with the labels that each got.

#981 docs(contributing): add link to Google Cloud Samples Style Guide
  CONTRIBUTING.md
Labels: samples

#982 chore: Switch test script to toys for better control over execution
  .kokoro/configure_gcloud.sh
  .kokoro/presubmit/common.cfg
  .kokoro/system_tests.sh
  .kokoro/system_tests/common.cfg
  .toys/kokoro-ci.rb
  Rakefile
  spec/kokoro-run-all.sh
Labels: samples

#992 chore: Don't generate junit xml output for presubmits
  .toys/kokoro-ci.rb
Labels: samples

#991 tests: Fix functions tests
  functions/Gemfile.lock
  functions/concepts/filesystem/Gemfile.lock
  functions/concepts/requests/Gemfile.lock
  functions/concepts/stateless/Gemfile.lock
  functions/env_vars/Gemfile.lock
  functions/firebase/analytics/Gemfile.lock
  functions/firebase/auth/Gemfile.lock
  functions/firebase/firestore/Gemfile.lock
  functions/firebase/reactive/Gemfile.lock
  functions/firebase/reactive/app.rb
  functions/firebase/remote_config/Gemfile.lock
  functions/firebase/rtdb/Gemfile.lock
  functions/helloworld/get/Gemfile.lock
  functions/helloworld/http/Gemfile.lock
  functions/helloworld/log/Gemfile.lock
  functions/helloworld/pubsub/Gemfile.lock
  functions/helloworld/storage/Gemfile.lock
  functions/http/content/Gemfile.lock
  functions/http/cors/Gemfile.lock
  functions/http/form_data/Gemfile.lock
  functions/http/method/Gemfile.lock
  functions/imagemagick/Gemfile.lock
  functions/slack/Gemfile.lock
  functions/test/firebase/reactive_test.rb
  functions/test/firebase/rtdb_test.rb
  functions/test/imagemagick_test.rb
  functions/test/slack_test.rb
  functions/tips/infinite_retries/Gemfile.lock
  functions/tips/lazy/Gemfile.lock
  functions/tips/retry/Gemfile.lock
  functions/tips/scopes/Gemfile.lock
Labels: samples

#990 tests: Fix iot and jobs tests on Ruby 3
  iot/Gemfile
  iot/Gemfile.lock
  iot/spec/iot_spec.rb
  jobs/Gemfile
  jobs/Gemfile.lock
Labels: samples

#993 chore: A helpful note in the CI log output
  .toys/kokoro-ci.rb
Labels: samples

#994 fix: Update google-style to 1.26
  .toys/kokoro-ci.rb
  Gemfile
  functions/slack/Gemfile.lock
  functions/test/slack_test.rb
  jobs/V3/custom_attribute_sample.rb
  spanner/database_leader_placement_samples.rb
  spanner/spanner_samples.rb
  spanner/tagging_samples.rb
Labels: samples

#995 chore: Ensure minitest-junit is part of the functions test bundle
  functions/Gemfile
  functions/Gemfile.lock
Labels: samples

#996 chore: Call flakybot on nightly runs
  .toys/kokoro-ci.rb
Labels: samples

#997 chore: Omit run/rails test from ci
  .toys/kokoro-ci.rb
Labels: samples

#788 Add comment about authenticated push JWT token validation
  appengine/pubsub/app.rb
Labels: cla: yes, samples

#999 fix(functions): add 2nd-gen region tag
  functions/helloworld/pubsub/app.rb
  functions/helloworld/storage/app.rb
Labels: api: cloudfunctions, samples

#959 Send the correct audience argument to JWT.decode
  getting-started/authenticating-users/app.rb
Labels: samples

#936 chore: retry job search that takes time to reflect
  jobs/Gemfile.lock
  jobs/spec/samples_spec.rb
  run/helloworld/spec/e2e_spec.rb
Labels: samples
