Repository GoogleCloudPlatform/ruby-docs-samples, pull requests merged in 2022-04, with the labels that each got.

#909 feat(spanner): add support for copy backup feature
  spanner/spanner_samples.rb
  spanner/spec/spanner_samples_spec.rb
Labels: do not merge, api: spanner, samples

#956 samples(spanner): Add samples for Postgres support in Spanner
  spanner/spanner_connect_postgresql_database.rb
  spanner/spanner_postgresql_add_column.rb
  spanner/spanner_postgresql_batch_dml.rb
  spanner/spanner_postgresql_cast_data_type.rb
  spanner/spanner_postgresql_create_database.rb
  spanner/spanner_postgresql_create_storing_index.rb
  spanner/spanner_postgresql_dml_getting_started_update.rb
  spanner/spanner_postgresql_dml_with_parameters.rb
  spanner/spanner_postgresql_functions.rb
  spanner/spanner_postgresql_identifier_case_sensitivity.rb
  spanner/spanner_postgresql_information_schema.rb
  spanner/spanner_postgresql_interleaved_table.rb
  spanner/spanner_postgresql_numeric_data_type.rb
  spanner/spanner_postgresql_order_nulls.rb
  spanner/spanner_postgresql_partitioned_dml.rb
  spanner/spanner_postgresql_query_parameter.rb
  spanner/spec/spanner_connect_postgresql_database_spec.rb
  spanner/spec/spanner_postgresql_add_column_spec.rb
  spanner/spec/spanner_postgresql_batch_dml_spec.rb
  spanner/spec/spanner_postgresql_cast_data_type_spec.rb
  spanner/spec/spanner_postgresql_create_database_spec.rb
  spanner/spec/spanner_postgresql_create_storing_index_spec.rb
  spanner/spec/spanner_postgresql_dml_getting_started_update_spec.rb
  spanner/spec/spanner_postgresql_dml_with_parameters_spec.rb
  spanner/spec/spanner_postgresql_functions_spec.rb
  spanner/spec/spanner_postgresql_helper.rb
  spanner/spec/spanner_postgresql_identifier_case_sensitivity_spec.rb
  spanner/spec/spanner_postgresql_information_schema_spec.rb
  spanner/spec/spanner_postgresql_interleaved_table_spec.rb
  spanner/spec/spanner_postgresql_numeric_data_type_spec.rb
  spanner/spec/spanner_postgresql_order_nulls_spec.rb
  spanner/spec/spanner_postgresql_partitioned_dml_spec.rb
  spanner/spec/spanner_postgresql_query_parameter_spec.rb
Labels: samples

#958 chore(functions/storage): clarify comments
  functions/helloworld/storage/app.rb
Labels: api: cloudfunctions, samples
